name:                palindrome-checker
version:             0.1.0.0
github:              "jacobprudhomme/palindrome-checker"
license:             BSD3
author:              "Jacob Prud'homme"
maintainer:          "jacob.pkmn@gmail.com"
copyright:           "©2020 Jacob Prud'homme"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A program to check if a word is a palindrome

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text

executables:
  palindrome-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - palindrome-checker
    - text
